"""Type stubs for the hallucinator native module."""

from typing import Optional

class Reference:
    """A parsed reference extracted from a PDF."""

    @property
    def raw_citation(self) -> str: ...
    @property
    def title(self) -> Optional[str]: ...
    @property
    def authors(self) -> list[str]: ...
    @property
    def doi(self) -> Optional[str]: ...
    @property
    def arxiv_id(self) -> Optional[str]: ...

class SkipStats:
    """Statistics about references that were skipped during extraction."""

    @property
    def url_only(self) -> int: ...
    @property
    def short_title(self) -> int: ...
    @property
    def no_title(self) -> int: ...
    @property
    def no_authors(self) -> int: ...
    @property
    def total_raw(self) -> int: ...

class ExtractionResult:
    """Result of extracting references from a PDF."""

    @property
    def references(self) -> list[Reference]: ...
    @property
    def skip_stats(self) -> SkipStats: ...
    def __len__(self) -> int: ...

class PdfExtractor:
    """A configurable PDF reference extractor.

    Set properties to customize regex patterns and thresholds, then call
    extraction methods.

    Example::

        ext = PdfExtractor()
        ext.section_header_regex = r"(?i)\\n\\s*Bibliografía\\s*\\n"
        ext.min_title_words = 3
        result = ext.extract("paper.pdf")
    """

    def __init__(self) -> None: ...

    # Config setters
    section_header_regex: str
    section_end_regex: str
    fallback_fraction: float
    ieee_segment_regex: str
    numbered_segment_regex: str
    fallback_segment_regex: str
    min_title_words: int
    max_authors: int

    def add_venue_cutoff_pattern(self, pattern: str) -> None: ...
    def set_venue_cutoff_patterns(self, patterns: list[str]) -> None: ...
    def add_quote_pattern(self, pattern: str) -> None: ...
    def set_quote_patterns(self, patterns: list[str]) -> None: ...
    def add_compound_suffix(self, suffix: str) -> None: ...
    def set_compound_suffixes(self, suffixes: list[str]) -> None: ...

    # Extraction methods
    def extract(self, path: str) -> ExtractionResult: ...
    def extract_text(self, path: str) -> str: ...
    def find_section(self, text: str) -> Optional[str]: ...
    def segment(self, text: str) -> list[str]: ...
    def parse_reference(
        self, text: str, prev_authors: Optional[list[str]] = None
    ) -> Optional[Reference]: ...
    def extract_from_text(self, text: str) -> ExtractionResult: ...
