/// Actions that the TUI can process, mapped from keyboard input or internal events.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Quit,
    NavigateBack,
    DrillIn,
    MoveUp,
    MoveDown,
    PageUp,
    PageDown,
    GoTop,
    GoBottom,
    CycleSort,
    ReverseSortDirection,
    CycleFilter,
    ToggleHelp,
    StartSearch,
    SearchInput(char),
    SearchConfirm,
    SearchCancel,
    NextMatch,
    PrevMatch,
    Retry,
    RetryAll,
    Export,
    AddFiles,
    #[allow(dead_code)] // planned feature: remove paper from queue
    RemovePaper,
    CopyToClipboard,
    OpenConfig,
    ToggleActivityPanel,
    SaveConfig,
    BuildDatabase,
    StartProcessing,
    ToggleSafe,
    ClickAt(u16, u16),
    CursorLeft,
    CursorRight,
    CursorHome,
    CursorEnd,
    DeleteForward,
    CycleConfigSection,
    Tick,
    Resize(u16, u16),
    None,
}
